things
enjarai/trickster pull request #77
Opened 2024-12-12 10:16 UTC by Vlue

theres stuff in here 

https://github.com/user-attachments/assets/e080c53e-9dae-4bd6-80f2-60585fe51669

2024-12-12 10:20 UTC, Vlue commented
adds:
- the ability to use slot references for the read and write spell tricks
- a new trick to clear the spell from a given slot
- a new necklace, the amethyst whorl, which recharges over time
- wrist pocket, and associated tricks
- not fully featured
 - proabably more stuff, some endec tomfoolery was done (it was not fun)

2024-12-17 00:40 UTC, StellarWitch7 requested changes
Please separate the spell-writing changes into a second pull request so that they can be merged separately. The rest of this PR will likely take longer to merge, as we need to get a texture for the whorl, and further discuss wristpocket's impact.

2025-01-08 00:24 UTC, StellarWitch7 commented
> Please separate the spell-writing changes into a second pull request so that they can be merged separately. The rest of this PR will likely take longer to merge, as we need to get a texture for the whorl, and further discuss wristpocket's impact.

Rai has done this.

2025-03-11 03:46 UTC, StellarWitch7 commented
@enjarai I believe we were to scrap what is left of this? Or am I misremembering... I no longer have access to that discussion.

2025-03-11 10:24 UTC, enjarai commented
Right uhh, I'm not sure about wristpocket. I think there's a nicer way to do something similar if we want to...

2025-03-11 19:01 UTC, StellarWitch7 commented
I agree. I'd like to close this PR.

2025-03-13 00:01 UTC, closed without merging